version: '3'

services:
  app:
    build: .
    container_name: flowershop
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - PG_HOST=flower_postgres
      - PG_USER=admin
      - PG_PASS=admin
      - PG_PORT=5432
      - PG_NAME=upsflower
      - PORT=8081

  db:
    image: 'postgres:latest'
    container_name: flower_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=upsflower